spring:
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl

    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.132.130:3306/db_book
    username: root
    password: 123


dir:
  mainDirectory : F://图书//

